---
# https://taskfile.dev
version: '3'

includes:
    go: ./tasks/go.yaml
    k8s: ./tasks/k8s.yaml
    argocd: ./tasks/argocd.yaml
    ts: ./tasks/ts.yaml

dotenv: [.env]

tasks:
    default:
        cmds:
            - task: go:fmt
            - task: go:lint
            - task: go:build
            - task: go:test

    services:
        desc: Set up services (aka ArgoCD) to use for tests.
        cmds:
            - task: k8s:cluster:delete
            - task: k8s:start
            - task: argocd:healthcheck
            - task: argocd:token

    devcontainer:
        desc: Test devcontainer changes
        cmds:
            - docker build -t devcontainer -f ./.devcontainer/Dockerfile .
