# https://taskfile.dev

version: '3'

tasks:
  build:
    desc: Build Dockerfile.
    cmds:
      - docker build -f Dockerfile -t tangle .

  shell:
    desc: Run shell in Docker container.
    cmds:
      - docker run -it --rm --entrypoint sh tangle

  run:
    desc: Run Docker container.
    cmds:
      - docker run -v `pwd`/integration:/config -e TANGLE_CONFIG_PATH=/config/tangle.yaml --network=host --env-file .env --rm -p 8082:8081 tangle
