apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-1
  labels:
    env: test
    foo: bar
spec:
  project: default
  source:
    repoURL: https://github.com/ivanklee86/tangle.git
    path: integration/kubernetes/example/manifests/1
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
