apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-2
  labels:
    env: prod
    baz: qux
spec:
  project: default
  source:
    repoURL: https://github.com/ivanklee86/tangle.git
    path: integration/kubernetes/example/manifests/2
    targetRevision: list_applications_api
  destination:
    server: https://kubernetes.default.svc
    namespace: default
