argo-cd:
  configs:
    cm:
      accounts.automation: apiKey
      accounts.automationProd: apiKey

    rbac:
      policy.csv: |
        p, role:automation, applications, get, default/*, allow
        g, automation, role:automation
        p, role:automationProd, applications, get, my-project/*, allow
        g, automationProd, role:automationProd

    params:
      server.insecure: true
